### PR TITLE
8 bit flag implementation in Deser and BytesSerializable.

### PR DESCRIPTION
**Pull request by bcdev-**

### CODE REVIEW

**Comment by Tolsi** [comment]
What is that and why?

**Comment by bcdev-** [comment]
They are binary flags [values] that can be used in transactions.
Let's imagine that you issue an asset. It has some bool values you can configure, like:
- Can it be traded by random people, or just by KYC people?
- Is this asset a currency?
- Does this asset have a field "KYC details file"?

With 8 bit flags you can encode all of those bool values in 3 bits instead of wasting 3 bytes on them.
I thought I'll use it in Encrypted Message Transaction [it turns out that I won't], but the code is already written&tested and may be useful for someone making new tx types in the future.

**Comment by Tolsi** [comment]
I understood, but now for us it seems useless, and we are opposed to the unused code in our project. Now I do not see the need to add a field with no specific purpose "for the future." Our team is now a lot of work and I think that if you make a new function as the encrypted messaging, then you have to work in the one branch for this feature and create one merge request when it is ready, instead of doing every single step as the incomprehensible merge request. I do not see how this and #143 can be useful to someone other than you in your work on the encrypted messaging. Please merge them and continue to work on the feature in one branch and then make a pull request when it is ready. Thank you.

**Comment by bcdev-** [comment]
No problem. :-)

**Pull request closed without merging**
