### PR TITLE
Added minimal generator balance

### PR DESCRIPTION
**Pull request by Tolsi**

### CODE REVIEW

**Comment by Tolsi** [comment]
Closes wavesplatform/Waves#42

**Comment by bcdev-** [comment]
That is a clever way to enforce that 10mil Waves are needed to execute this attack. :-)

**Comment by bcdev-** [comment]
What I've said is incorrect. With this code for the cost of a 100k you could potentially double-spend 9 blocks, which could be enough to heist an exchange. :-)
100k >>> 1k, but still "potentially" doable.

However, I don't think we need to worry about that right now. :-P

**Comment by Tolsi** [comment]
@bcdev- then we have to tell everyone that they have used translations only 10 confirmations. NXT have 10 also

**Pull request merged**
