### PR TITLE
Increasing generation balance depth

### PR DESCRIPTION
**Pull request by Tolsi**
This closes wavesplatform/Waves#42

### CODE REVIEW

**Comment by bcdev-** [comment]
Is it wise to weaken this critical variable? NXT uses 1440 and I don't really think it's a good idea to use anything lower...

**Comment by Tolsi** [comment]
@bcdev- it does not change almost nothing

**Comment by bcdev-** [comment]
Except for a security margin. But if you think that 1000 is enough, fine. :-)

**Comment by Tolsi** [comment]
we seen a scientific article, where it says that for maximum security, this value should tend to infinity, but we can not do it

**Pull request merged**
